config/routes.rb
Rails.application.routes.draw do
  patch 'links/:id' => 'links#update', as: :links
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
  }
  get 'dashboard', to: "dashboard#index"
  root 'dashboard#index'
  get 'appearance', to: "dashboard#appearance"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get ':id', to: 'dashboard#show', as: :user
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  <%= link_to 'Public Profile', current_user, class: "navbar-brand", data: { turbo: false } %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Link Manager', dashboard_path, class: "nav-link", data: { turbo: false } %>
        </li>
        <li class="nav-item">
          <%= link_to 'Profile', appearance_path, class: "nav-link", data: { turbo: false } %>
        </li>
      </ul>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= image_tag(current_user.avatar, class:"avatar-image-sm") if current_user.avatar.attached? %>
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

            <li><%= link_to 'My Account', edit_user_registration_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Log Out", destroy_user_session_path, class: 'dropdown-item', data: {turbo_method: "delete"} %></li>
          </ul>
        </li>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LinktreeClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body class="profile-page">
    <%= render partial: 'layouts/navbar' if @should_render_navbar %>
    <%= render partial: 'layouts/alerts' %>
    <%= yield %>
    <footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </footer>
  </body>
</html>